# Generated by Django 5.0.6 on 2026-04-30 22:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_completed', 'Booking Completed'), ('payment_initiated', 'Payment Initiated'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed'), ('payout_sent', 'Payout Sent'), ('user_registered', 'User Registered'), ('user_kyc_submitted', 'KYC Submitted'), ('user_kyc_approved', 'KYC Approved'), ('user_kyc_rejected', 'KYC Rejected'), ('order_created', 'Order Created'), ('competition_entry', 'Competition Entry')], db_index=True, help_text='Category of the platform event.', max_length=40)),
                ('reference_id', models.UUIDField(blank=True, db_index=True, help_text='UUID of the related object (booking, payment, order, etc.).', null=True)),
                ('reference_type', models.CharField(blank=True, help_text="Type label for reference_id, e.g. 'booking', 'payment'.", max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary amount at event time. NUMERIC(12,2) — never float.', max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, help_text='ISO 4217 currency code (from region). Blank for non-monetary events.', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured snapshot of relevant data at event time.')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP of the request that triggered the event. Null for system events.', null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered the event. Null for system-generated events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'analytics_audit_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OwnerEarningsSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(help_text='Calendar year, e.g. 2025.')),
                ('month', models.PositiveSmallIntegerField(help_text='Calendar month 1–12.')),
                ('gross_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue before platform fee deduction. NUMERIC(12,2).', max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform commission charged for the period. NUMERIC(12,2).', max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, help_text='gross_revenue - platform_fee. NUMERIC(12,2).', max_digits=12)),
                ('currency', models.CharField(help_text="ISO 4217 currency code sourced from the owner's region.", max_length=3)),
                ('booking_count', models.PositiveIntegerField(default=0, help_text='Number of completed bookings in this period.')),
                ('owner', models.ForeignKey(help_text='Boat owner this summary belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='earnings_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Owner Earnings Summary',
                'verbose_name_plural': 'Owner Earnings Summaries',
                'db_table': 'analytics_owner_earnings',
                'ordering': ['-year', '-month'],
                'unique_together': {('owner', 'year', 'month')},
            },
        ),
    ]
