# Generated by Django 5.0.6 on 2026-05-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_blockeddate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='blockeddate',
            name='unique_blockeddate_yacht_date',
        ),
        migrations.AlterField(
            model_name='blockeddate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='currency',
            field=models.CharField(help_text="ISO 4217 currency code copied from region at creation. e.g. 'EGP', 'AED'.", max_length=3),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag — never hard-delete user-facing records.'),
        ),
        migrations.AlterField(
            model_name='yachtmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='blockeddate',
            unique_together={('yacht', 'date')},
        ),
    ]
