# Generated by SeaConnect Sprint 13C — pgvector semantic search (ADR-019)
#
# Adds a nullable 768-dim VectorField to bookings_yacht.
#
# Requires the `vector` PostgreSQL extension — enabled by VectorExtension()
# below, which runs `CREATE EXTENSION IF NOT EXISTS vector` inside the
# migration so it is idempotent on re-runs.
#
# Zero-downtime safety (see CLAUDE.md migration rules):
#   - Column is nullable → safe to ADD without a table rewrite.
#   - No NOT NULL constraint → backfill can happen asynchronously via
#     `generate_yacht_embedding` Celery task.

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_remove_blockeddate_unique_blockeddate_yacht_date_and_more"),
    ]

    operations = [
        # Ensure the pgvector extension exists in the target database.
        # CREATE EXTENSION IF NOT EXISTS is idempotent and safe to run in CI.
        pgvector.django.VectorExtension(),
        migrations.AddField(
            model_name="yacht",
            name="embedding",
            field=pgvector.django.VectorField(
                blank=True,
                dimensions=768,
                help_text="768-dim sentence embedding for semantic search (ADR-019).",
                null=True,
            ),
        ),
    ]
