# Generated by Django 5.0.6 on 2026-05-17 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_yacht_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aggregate average review rating (0.00–5.00). Updated by review write-back.', max_digits=3),
        ),
        migrations.AddField(
            model_name='yacht',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of approved reviews. Updated by review write-back.'),
        ),
        migrations.CreateModel(
            name='YachtReview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating 1–5.')),
                ('title', models.CharField(blank=True, help_text='Short review headline (optional).', max_length=200)),
                ('body', models.TextField(help_text='Full review text.')),
                ('booking', models.ForeignKey(blank=True, help_text='Completed booking that unlocks the review privilege.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='bookings.booking')),
                ('customer', models.ForeignKey(help_text='Customer who wrote the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('yacht', models.ForeignKey(help_text='Yacht being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookings.yacht')),
            ],
            options={
                'verbose_name': 'Yacht Review',
                'verbose_name_plural': 'Yacht Reviews',
                'db_table': 'bookings_yacht_review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['yacht', 'created_at'], name='idx_review_yacht_date'), models.Index(fields=['customer'], name='idx_review_customer')],
                'unique_together': {('yacht', 'customer')},
            },
        ),
    ]
