# Generated by Django 5.0.6 on 2026-05-17 10:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_yacht_review_and_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(help_text='Short description of the dispute (≤500 chars; Arabic accommodated).', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', help_text='Current lifecycle state of the dispute.', max_length=20)),
                ('resolution', models.TextField(blank=True, help_text='Admin-written resolution note. Required when status→resolved.')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the dispute was resolved.', null=True)),
                ('booking', models.ForeignKey(help_text='Booking this dispute concerns.', on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='bookings.booking')),
                ('raised_by', models.ForeignKey(help_text='User (customer or owner) who opened the dispute.', on_delete=django.db.models.deletion.PROTECT, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Admin user who resolved the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute',
                'verbose_name_plural': 'Disputes',
                'db_table': 'bookings_dispute',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='idx_dispute_status'), models.Index(fields=['booking'], name='idx_dispute_booking'), models.Index(fields=['raised_by'], name='idx_dispute_raised_by')],
            },
        ),
    ]
