# Generated by Django 5.0.6 on 2026-05-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Aggregate average review rating (0.00–5.00). Updated by review write-back.', max_digits=3),
        ),
    ]
