# Generated by Django 5.0.6 on 2026-04-30 21:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('push_enabled', models.BooleanField(default=True, help_text='Allow push notifications via FCM.')),
                ('email_enabled', models.BooleanField(default=True, help_text='Allow transactional email notifications.')),
                ('booking_reminders', models.BooleanField(default=True, help_text='Send 24-hour-before-trip reminder push.')),
                ('marketing', models.BooleanField(default=False, help_text='Promotional / marketing messages. Requires explicit user opt-in.')),
                ('user', models.OneToOneField(help_text='The user these preferences belong to.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notifications_preference',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('booking_reminder', 'Booking Reminder'), ('payment_received', 'Payment Received'), ('payout_sent', 'Payout Sent'), ('competition_reminder', 'Competition Reminder')], db_index=True, help_text='Semantic type — used for deep-linking and preference filtering.', max_length=40)),
                ('channel', models.CharField(choices=[('push', 'Push (FCM)'), ('email', 'Email'), ('in_app', 'In-App')], db_index=True, help_text='Delivery channel for this row.', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read')], db_index=True, default='pending', help_text='Lifecycle state of this delivery attempt.', max_length=10)),
                ('title_ar', models.CharField(help_text='Notification title in Arabic (primary).', max_length=200)),
                ('title_en', models.CharField(help_text='Notification title in English.', max_length=200)),
                ('body_ar', models.TextField(help_text='Notification body in Arabic (primary).')),
                ('body_en', models.TextField(help_text='Notification body in English.')),
                ('reference_id', models.UUIDField(blank=True, help_text='UUID of the related object, e.g. booking.id.', null=True)),
                ('reference_type', models.CharField(blank=True, help_text="Type name of the related object, e.g. 'booking'.", max_length=40)),
                ('sent_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the message was accepted by the delivery provider.', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='UTC timestamp when the user read this notification (in-app only).', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Error detail if status=failed.')),
                ('recipient', models.ForeignKey(help_text='User who will receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'channel', 'status'], name='idx_notif_recipient_ch_status'), models.Index(fields=['recipient', 'notification_type'], name='idx_notif_recipient_type'), models.Index(fields=['reference_type', 'reference_id'], name='idx_notif_reference')],
            },
        ),
    ]
