"""Django admin registrations for the analytics app.

AuditLog is registered as read-only across all fields to enforce the
append-only contract — no updates or deletes via the admin interface.
"""
from django.contrib import admin

from .models import AuditLog, OwnerEarningsSummary


@admin.register(AuditLog)
class AuditLogAdmin(admin.ModelAdmin):  # type: ignore[type-arg]
    """Admin view for the append-only AuditLog.

    All fields are read-only to enforce the immutability contract.
    Provides filtering by event type and reference type, and search by actor email.
    """

    list_display = [
        "event_type",
        "actor",
        "reference_type",
        "amount",
        "currency",
        "created_at",
    ]
    list_filter = ["event_type", "reference_type"]
    search_fields = ["actor__email"]
    ordering = ["-created_at"]
    date_hierarchy = "created_at"

    # All fields read-only — AuditLog rows are immutable after creation.
    readonly_fields = [
        "id",
        "event_type",
        "actor",
        "reference_id",
        "reference_type",
        "amount",
        "currency",
        "metadata",
        "ip_address",
        "created_at",
        "updated_at",
    ]

    def has_add_permission(self, request) -> bool:  # type: ignore[override]
        """Prevent creating audit log entries via the admin — use log_event()."""
        return False

    def has_change_permission(self, request, obj=None) -> bool:  # type: ignore[override]
        """Prevent any edits to audit log rows — they are immutable."""
        return False

    def has_delete_permission(self, request, obj=None) -> bool:  # type: ignore[override]
        """Prevent deletion of audit log rows — they are append-only."""
        return False


@admin.register(OwnerEarningsSummary)
class OwnerEarningsSummaryAdmin(admin.ModelAdmin):  # type: ignore[type-arg]
    """Admin view for monthly owner earnings rollups.

    Read-only — summaries are generated by Celery Beat, not by admin input.
    """

    list_display = [
        "owner",
        "year",
        "month",
        "gross_revenue",
        "platform_fee",
        "net_revenue",
        "currency",
        "booking_count",
    ]
    list_filter = ["year", "month", "currency"]
    search_fields = ["owner__email"]
    ordering = ["-year", "-month"]

    readonly_fields = [
        "id",
        "owner",
        "year",
        "month",
        "gross_revenue",
        "platform_fee",
        "net_revenue",
        "currency",
        "booking_count",
        "created_at",
        "updated_at",
    ]

    def has_add_permission(self, request) -> bool:  # type: ignore[override]
        return False

    def has_change_permission(self, request, obj=None) -> bool:  # type: ignore[override]
        return False

    def has_delete_permission(self, request, obj=None) -> bool:  # type: ignore[override]
        return False
