/* global React */
const { useState, useEffect, useMemo } = React;

// ── Data (shared) ─────────────────────────────────────
const BOATS = [
  {
    id: 'b1',
    name: 'البحر الأحمر',
    nameEn: 'Al Bahr Al Ahmar',
    type: 'يخت صيد فاخر',
    typeEn: 'Premium Fishing Yacht',
    capt: 'الربان محمود سيف',
    captEn: 'Capt. Mahmoud Seif',
    region: 'الغردقة',
    regionEn: 'Hurghada',
    coords: '27.2579°N · 33.8116°E',
    length: 42,
    pax: 8,
    year: 2021,
    price: 3800,
    rating: 4.92,
    reviews: 148,
    img: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1400&q=80',
    tag: 'مُعتمد',
    tagEn: 'VERIFIED',
  },
  {
    id: 'b2',
    name: 'نور الشاطئ',
    nameEn: 'Nour Al Shati',
    type: 'قارب صيد متوسط',
    typeEn: 'Mid-size Fishing',
    capt: 'الربان إبراهيم الغرباوي',
    captEn: 'Capt. Ibrahim Gharbawi',
    region: 'الإسكندرية',
    regionEn: 'Alexandria',
    coords: '31.2001°N · 29.9187°E',
    length: 28,
    pax: 6,
    year: 2019,
    price: 1800,
    rating: 4.81,
    reviews: 92,
    img: 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=1400&q=80',
    tag: 'الأكثر حجزاً',
    tagEn: 'TOP BOOKED',
  },
  {
    id: 'b3',
    name: 'ريح البحر',
    nameEn: 'Reeh Al Bahr',
    type: 'يخت عائلي',
    typeEn: 'Family Yacht',
    capt: 'الربان كريم فتحي',
    captEn: 'Capt. Kareem Fathy',
    region: 'شرم الشيخ',
    regionEn: 'Sharm El Sheikh',
    coords: '27.9158°N · 34.3299°E',
    length: 38,
    pax: 12,
    year: 2022,
    price: 4400,
    rating: 4.95,
    reviews: 211,
    img: 'https://images.unsplash.com/photo-1566024287286-457247b70310?auto=format&fit=crop&w=1400&q=80',
    tag: 'جديد',
    tagEn: 'NEW',
  },
  {
    id: 'b4',
    name: 'فلوكة النيل',
    nameEn: 'Felucca Al Nil',
    type: 'فلوكة تقليدية',
    typeEn: 'Traditional Felucca',
    capt: 'الربان أحمد العربي',
    captEn: 'Capt. Ahmed Al Araby',
    region: 'الأقصر',
    regionEn: 'Luxor',
    coords: '25.6872°N · 32.6396°E',
    length: 32,
    pax: 10,
    year: 2018,
    price: 950,
    rating: 4.88,
    reviews: 304,
    img: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=1400&q=80',
    tag: 'نيلي',
    tagEn: 'NILE',
  },
  {
    id: 'b5',
    name: 'أطلانتس',
    nameEn: 'Atlantis',
    type: 'يخت فاخر',
    typeEn: 'Luxury Charter',
    capt: 'الربان يوسف منصور',
    captEn: 'Capt. Youssef Mansour',
    region: 'الغردقة',
    regionEn: 'Hurghada',
    coords: '27.2579°N · 33.8116°E',
    length: 56,
    pax: 16,
    year: 2023,
    price: 8900,
    rating: 4.97,
    reviews: 76,
    img: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=1400&q=80',
    tag: 'مميّز',
    tagEn: 'FEATURED',
  },
  {
    id: 'b6',
    name: 'صياد الصبح',
    nameEn: 'Sayyad Al Sobh',
    type: 'قارب صيد صغير',
    typeEn: 'Small Fishing Boat',
    capt: 'الربان سامي حسن',
    captEn: 'Capt. Samy Hassan',
    region: 'دهب',
    regionEn: 'Dahab',
    coords: '28.5091°N · 34.5136°E',
    length: 22,
    pax: 4,
    year: 2020,
    price: 1200,
    rating: 4.79,
    reviews: 56,
    img: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80',
    tag: 'مُعتمد',
    tagEn: 'VERIFIED',
  },
];

const REGIONS = [
  { ar: 'كل السواحل', en: 'All coasts', count: 183 },
  { ar: 'الغردقة', en: 'Hurghada', count: 68 },
  { ar: 'الإسكندرية', en: 'Alexandria', count: 42 },
  { ar: 'شرم الشيخ', en: 'Sharm El Sheikh', count: 31 },
  { ar: 'دهب', en: 'Dahab', count: 14 },
  { ar: 'بورسعيد', en: 'Port Said', count: 12 },
  { ar: 'الأقصر — النيل', en: 'Luxor — Nile', count: 9 },
  { ar: 'أسوان — النيل', en: 'Aswan — Nile', count: 7 },
];

const GEAR = [
  { brand: 'SHIMANO', title: 'سنارة ستيلا 8000', price: 12400, img: 'https://images.unsplash.com/photo-1545056453-f0359c3df6db?auto=format&fit=crop&w=600&q=80' },
  { brand: 'DAIWA', title: 'بكرة سالتيجا 14000', price: 8900, img: 'https://images.unsplash.com/photo-1559285988-b11d3ab6ccc0?auto=format&fit=crop&w=600&q=80' },
  { brand: 'PENN', title: 'طقم صنارة كاملة', price: 3200, img: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?auto=format&fit=crop&w=600&q=80' },
  { brand: 'RAPALA', title: 'طعوم صناعية × 12', price: 780, img: 'https://images.unsplash.com/photo-1513039464697-c75e46a88020?auto=format&fit=crop&w=600&q=80' },
  { brand: 'GARMIN', title: 'جهاز كشف أسماك STRIKER', price: 6400, img: 'https://images.unsplash.com/photo-1568205612837-017257d2310a?auto=format&fit=crop&w=600&q=80' },
  { brand: 'PLANO', title: 'صندوق معدات مزدوج', price: 540, img: 'https://images.unsplash.com/photo-1564419320408-49c30c47a2e7?auto=format&fit=crop&w=600&q=80' },
  { brand: 'COLUMBIA', title: 'قميص صيد طويل الكم', price: 890, img: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?auto=format&fit=crop&w=600&q=80' },
  { brand: 'MUSTAD', title: 'صناصيل بحرية × 50', price: 120, img: 'https://images.unsplash.com/photo-1580137189272-c9379f8864fd?auto=format&fit=crop&w=600&q=80' },
];

const COMPETITIONS = [
  { d: 12, m: 'MAY', title: 'بطولة البحر الأحمر للصيد الكبير', sub: 'SAFAGA MARINA · 14 HRS · 3 ROUNDS', participants: 84, prize: '120K', fee: 500 },
  { d: 26, m: 'MAY', title: 'كأس الاسكندرية السنوي', sub: 'ABU QIR · 8 HRS · DEEP SEA', participants: 56, prize: '60K', fee: 300 },
  { d: 8, m: 'JUN', title: 'بطولة شرم للتونة', sub: 'SHARM MARINA · 12 HRS · PELAGIC', participants: 42, prize: '90K', fee: 450 },
  { d: 19, m: 'JUN', title: 'مهرجان النيل للصيد الرياضي', sub: 'LUXOR · 6 HRS · CATCH & RELEASE', participants: 120, prize: '40K', fee: 150 },
];

const REVIEWS = [
  {
    name: 'عمرو عبد الحليم',
    nameEn: 'Amr Abdel-Halim',
    date: '2026-03-14',
    stars: 5,
    excerpt: 'رحلة استثنائية — الربان خبير في مواقع التونة.',
    body: 'كنا مجموعة من خمسة أشخاص وكان الطاقم محترفاً. اليخت نظيف ومجهز بأحدث الأجهزة. صدنا تونة كبيرة في أول ساعتين. التجربة تستحق كل قرش.',
  },
  {
    name: 'Liam Carter',
    nameEn: 'Liam Carter',
    date: '2026-02-28',
    stars: 5,
    excerpt: 'Best fishing day I’ve had in Egypt.',
    body: 'Captain knew every productive reef in the area. Gear was top-shelf Shimano. Booked via app — confirmation within 20 minutes. Will book again next trip.',
  },
  {
    name: 'نادية الشامي',
    nameEn: 'Nadia El-Shamy',
    date: '2026-02-11',
    stars: 4,
    excerpt: 'عائلي ومريح، لكن مكيف الغرفة السفلية ضعيف.',
    body: 'حجزنا لمجموعة عائلية في يوم الخميس. الأطفال استمتعوا كثيراً والربان كان صبوراً معهم. الشيء الوحيد هو أن التكييف في الغرفة السفلية لم يكن قوياً بما يكفي في الحر.',
  },
];

// export to window
Object.assign(window, { BOATS, REGIONS, GEAR, COMPETITIONS, REVIEWS });
