# Generated by Django 5.0.6 on 2026-05-06 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.CreateModel(
            name='BoatOwnerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_started', max_length=20)),
                ('national_id_verified', models.BooleanField(default=False)),
                ('vessel_docs_verified', models.BooleanField(default=False)),
                ('captain_license_verified', models.BooleanField(default=False)),
                ('insurance_verified', models.BooleanField(default=False)),
                ('inspection_passed', models.BooleanField(default=False)),
                ('bank_account_configured', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_boat_owner_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(help_text="Matches an onboarding step: 'national_id', 'vessel_docs', 'captain_license', 'insurance', 'inspection', 'bank_account'.", max_length=50)),
                ('file', models.FileField(upload_to='kyc/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.boatownerprofile')),
            ],
            options={
                'db_table': 'accounts_kyc_document',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='boatownerprofile',
            index=models.Index(fields=['kyc_status'], name='idx_owner_profile_kyc_status'),
        ),
    ]
