# Generated by Django 5.0.6 on 2026-04-30 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_egypt'),
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Arabic competition name (primary).', max_length=200)),
                ('title_en', models.CharField(help_text='English competition name.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateTimeField(help_text='UTC deadline after which no new entries are accepted.')),
                ('entry_fee', models.DecimalField(decimal_places=2, help_text='Entry fee amount. Currency comes from region.currency (ADR-018).', max_digits=12)),
                ('prize_pool', models.DecimalField(decimal_places=2, help_text='Total prize pool. Currency comes from region.currency (ADR-018).', max_digits=12)),
                ('max_participants', models.PositiveIntegerField(default=100, help_text='Maximum number of confirmed participants allowed.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('rules', models.TextField(blank=True, help_text='Competition rules and scoring criteria.')),
                ('created_by', models.ForeignKey(help_text='Staff or admin user who created this competition.', on_delete=django.db.models.deletion.PROTECT, related_name='competitions_created', to=settings.AUTH_USER_MODEL)),
                ('departure_port', models.ForeignKey(blank=True, help_text='Optional departure port for this competition.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='core.departureport')),
                ('region', models.ForeignKey(help_text='Region this competition runs in. Currency is derived from region.currency.', on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to='core.region')),
            ],
            options={
                'verbose_name': 'Competition',
                'verbose_name_plural': 'Competitions',
                'db_table': 'competitions_competition',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('disqualified', 'Disqualified'), ('withdrawn', 'Withdrawn')], default='registered', max_length=20)),
                ('payment_ref', models.CharField(blank=True, help_text='Payment gateway reference for the entry fee transaction.', max_length=100)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Competition Entry',
                'verbose_name_plural': 'Competition Entries',
                'db_table': 'competitions_entry',
                'ordering': ['-created_at'],
                'unique_together': {('competition', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CatchLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_kg', models.DecimalField(decimal_places=3, help_text='Fish weight in kilograms.', max_digits=8)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Fish length in centimetres (optional).', max_digits=6, null=True)),
                ('caught_at', models.DateTimeField(help_text='UTC timestamp when the fish was caught.')),
                ('photo_url', models.URLField(blank=True, help_text='URL of catch verification photo.')),
                ('verified', models.BooleanField(default=False, help_text='Set to True by a competition judge after verification.')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catch_logs', to='weather.fishingspecies')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='competitions.competitionentry')),
            ],
            options={
                'verbose_name': 'Catch Log',
                'verbose_name_plural': 'Catch Logs',
                'db_table': 'competitions_catch',
                'ordering': ['-weight_kg'],
            },
        ),
    ]
