# Generated by Django 5.0.6 on 2026-04-29 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_seed_egypt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingSpecies',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'weather_fishing_species',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCache',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('wind_direction_deg', models.SmallIntegerField(blank=True, null=True)),
                ('wave_height_m', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('wave_period_s', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weather_code', models.SmallIntegerField(blank=True, help_text='WMO weather interpretation code.', null=True)),
                ('advisory_level', models.CharField(choices=[('safe', 'Safe'), ('caution', 'Caution'), ('danger', 'Danger')], default='safe', max_length=10)),
                ('fetched_at', models.DateTimeField(help_text='UTC timestamp when fetched from Open-Meteo.')),
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather_cache', to='core.departureport')),
            ],
            options={
                'db_table': 'weather_cache',
            },
        ),
        migrations.CreateModel(
            name='FishingSeason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.SmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('is_peak', models.BooleanField(default=False)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishing_seasons', to='core.departureport')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='weather.fishingspecies')),
            ],
            options={
                'db_table': 'weather_fishing_season',
                'ordering': ['species', 'port', 'month'],
                'unique_together': {('species', 'port', 'month')},
            },
        ),
    ]
